version: "3.9"
services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    extra_hosts:
      - "localhost:192.168.1.74"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
