global:
  scrape_interval: 60s
  evaluation_interval: 60s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["192.168.1.74:8083"]
  # - job_name: postgres-exporter
  #   static_configs:
  #     - targets: ["postgres-exporter:9187"]
