{
 "title": "Greenhouse Hydroponics",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Air Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "air_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "air_temperature", "legendFormat": "__auto" },
    { "expr": "water_temperature", "legendFormat": "__auto" },
    { "expr": "hy_solar_panel_charging", "legendFormat": "__auto" },
    { "expr": "hy_water_pump_on + 1.5", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "air_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Water Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "water_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "water_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Voltage In",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "voltage_in", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Voltage (Battery)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 16 },
   "targets": [
    { "expr": "voltage_in", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "voltage_in", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Solar Charging",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hy_solar_panel_charging", "legendFormat": " " }
   ]
  },
  {
   "title": "Water Pump",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hy_water_pump_on", "legendFormat": " " }
   ]
  },
  {
   "title": "Current & Voltage (Battery)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 24 },
   "targets": [
    { "expr": "shunt_current", "legendFormat": "__auto" },
    { "expr": "shunt_voltage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "INA219 Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 24 },
   "targets": [
    { "expr": "power_calc", "legendFormat": "__auto" },
    { "expr": "power_register", "legendFormat": "__auto" }
   ]
  }
 ]
}