{
 "title": "Greenhouse Hydroponics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "air_temperature", "legendFormat": "__auto" },
    { "expr": "water_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Voltage In",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "voltage_in", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Voltage (Battery)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    { "expr": "voltage_in", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "INA219 Shunt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
   "targets": [
    { "expr": "shunt_current", "legendFormat": "__auto" },
    { "expr": "shunt_voltage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "INA219 Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
   "targets": [
    { "expr": "power_calc", "legendFormat": "__auto" },
    { "expr": "power_register", "legendFormat": "__auto" }
   ]
  }
 ]
}