{
 "title": "Greenhouse Hydroponics",
 "time": { "from": "2022-08-25T23:35:50.000Z", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Air Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "air_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 0 },
   "targets": [
    { "expr": "air_temperature", "legendFormat": "__auto" },
    { "expr": "water_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Water Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "water_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Voltage In",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "voltage_in", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Voltage (Battery)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 10 },
   "targets": [
    { "expr": "voltage_in", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Solar Charging",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "hy_solar_panel_charging", "legendFormat": " " }
   ]
  },
  {
   "title": "Current & Voltage (Battery)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 18 },
   "targets": [
    { "expr": "shunt_current", "legendFormat": "__auto" },
    { "expr": "shunt_voltage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "INA219 Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 18 },
   "targets": [
    { "expr": "power_calc", "legendFormat": "__auto" },
    { "expr": "power_register", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current & Voltage (Battery)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 26 },
   "targets": [
    { "expr": "hy_solar_panel_charging", "legendFormat": "__auto" }
   ]
  }
 ]
}