name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/HydroponicsServer.API/WebAPI/HydroponicsServer.WebAPI.csproj
    - name: Build
      run: dotnet build ./src/HydroponicsServer.API/ --no-restore
    - name: Test
      run: dotnet test ./src/HydroponicsServer.API/ --no-build --verbosity normal
